### ISSUE TITLE
Feature request: A public demo

### ISSUE THREAD

**Issue by JensRantil** [Pronovix/walkhub-service#11]
Couldn't find in README nor on http://pronovix.com/walkhub.

**Comment by Nagygyorgy** [comment]
Hi JensRantil! Please find it here: http://pronovix.us6.list-manage1.com/subscribe?u=5756ad9696bad5dc41c7b93f9&id=7547965b41

**Comment by JensRantil** [comment]
Hi @Nagygyorgy. It's not public.

**Comment by Nagygyorgy** [comment]
Could you explain it a bit further what you experience? As it works fine for us in different browsers and in incognito mode also.

**Comment by JensRantil** [comment]
> Could you explain it a bit further what you experience? 

Sure! This is my experience: I go to FOSDEM, I listen to a presentation by someone from your team, I get curious and would like to see a quick demo tutorial of the open source product he presents on stage (which clearly he probably should have given). I want a public demo. Without scheduling a time with someone. Without sharing my personal contact information. Simply a link. I create this issue. A public demo is one where I don't need to get in touch with a sales representative to test something out.

> As it works fine for us in different browsers and in incognito mode also.

Where? Is there a public demo somewhere?

**Comment by JensRantil** [comment]
Hello! Why was this closed?

**Comment by tamasd** [comment]
The public demo was https://walkhub.net, but we are closing it down, because we are refocusing our business. The source code and the docker file (recommended way of trying out and deploying WalkHub) will remain available on GitHub.
