### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by burkeallen** [Pronovix/walkhub-service#21]
go version go1.5 linux/amd64
node.js version 4.4.5

see attached npm log file
[npm-debug.zip](https://github.com/Pronovix/walkhub-service/files/299105/npm-debug.zip)

also some kind of documentation would be really nice, it is great you are providing this as open source, but you are making it extremely difficult for others to jump in and test this and then be in a position to help contribute improvements etc.

**Comment by tamasd** [comment]
It seems that some dependency for node-gyp is missing. This might help you: https://github.com/nodejs/node-gyp#installation

WalkHub does not use node-gyp directly, it must be one of its dependencies that pulls this is in.

What kind of documentation do you miss?

**Comment by burkeallen** [comment]
1.a list of dependencies would be a great start, as apparently the install
script is not foolproof and the current list, og Go, postgress, and node
are not complete.
2. after the install completes, then what?
3. is this running under its own http services or does it require apache,
nginx, etc.?
4. you reference walkhub being like Git, here is Git's documentation -
https://git-scm.com/doc  walkhub is defintely lacking.

not trying to be harsh or judgemental, just really hoping for a great open
source solution here, and right now walkhub does not seem mature enough.

_Burke Allen_
_President & CEO at NovoLogic, Inc_
_direct *_770-609-2300 mobile 770-265-4362 *
burke@novologic.com | www.novologic.com

| http://twitter.com/novologic

**Comment by kvantomme** [comment]
Hi Allen!

We are bank rolling the project from our consultancy income, and while we care deeply about documentation, we don't always have the available time to do this perfect on our own. It is also very hard to document the problems we don't have as advanced users.

That said, I think there is a way that we can both get what we need faster, while making the project more successful. If I can get you some private time with one of our developers to help you get through the snags you are experiencing, would you be willing to write up what you learned so we can add it to the documentation? In open source projects the best documentation often comes from new users. 

I'm not asking you to write our docs, just write up what you think is missing, and our technical writers will add it to the documentation.
